services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 29154698
      POSTGRES_DB: PFE
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: node_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
